# REQUIRED CHANGES

title: Olivia Muehlberg | Portfolio

url: "https://omuehlberg.github.io"

baseurl: "/portfolio"


# OPTIONAL CHANGES

techfolio-theme: default.css

rouge-theme: github.css


# OPTIONAL PERSONALIZATION

description: MS Business Analytics | Hockey Data Analyst

author: Olivia Muehlberg


# DON'T CHANGE BELOW

markdown: kramdown

kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge

strict_front_matter: true

mathjax: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

include:
  - _data

plugins:
  - jekyll-gist
